### ISSUE TITLE
Share and collect validator signatures over UCCB events

### ISSUE THREAD

**Issue by DrZoltanFazekas** [Zilliqa/zq2#1016]
When validators sign a `Relayed` event, they shall broadcast their signatures using libp2p, and they shall collect and store the signatures broadcast by other validators.

On every new signature received, validators shall check if the signatures collected have reached the supermajority and mark the respective UCCB `nonce` as ready, meaning that a UCCB transaction can be submitted to the target chain,

**Comment by yaron-zilliqa** [comment]
Implemented in https://github.com/Zilliqa/zq2/pull/1354
