### ISSUE TITLE
Publish checkpoints

### ISSUE THREAD

**Issue by DrZoltanFazekas** [Zilliqa/zq2#1021]
Once per day (at every `24 * blocks_per_hour` blocks) we shall
- export a weak-subjectivity checkpoint
- make the state available for download
- publish the root hash on the website
- share the root hash with Rahul to publish on social channels
- publish the root hash on Ethereum mainnet so that it can be retrieved from a contract

**Comment by theo-zil** [comment]
@DrZoltanFazekas I've marked it as Done because the node functionality has been implemented - shall we open another ticket for devops for the actual publishing part?
