### ISSUE TITLE
Implement EIP-1898

### ISSUE THREAD

**Issue by rrw-zilliqa** [Zilliqa/zq2#1033]
https://eips.ethereum.org/EIPS/eip-1898 is required by TheGraph under some circumstances, and is probably in any case a good thing to implement. We should do so at a convenient moment.

**Comment by JamesHinshelwood** [comment]
Strongly consider using file:///home/james/zq/zq2/target/doc/alloy_rpc_types/enum.BlockId.html when implementing this rather than re-implementing yourself :)

**Comment by JamesHinshelwood** [comment]
Resolved by #1079
