### ISSUE TITLE
Implement proof-of-possession for `deposit` method in deposit contract.

### ISSUE THREAD

**Issue by JamesHinshelwood** [Zilliqa/zq2#1069]
This might requite some BLS precompiles first. Discuss and design before jumping in :)

**Comment by shawn-zil** [comment]
This is where it needs to go.
https://github.com/Zilliqa/zq2/blob/ff923524b14ced96c5c003d7b4b77f1ae22caa5b/zilliqa/src/contracts/deposit.sol#L63
