### ISSUE TITLE
Implement PoS-compatible ValidatorManager

### ISSUE THREAD

**Issue by DrZoltanFazekas** [Zilliqa/zq2#1126]
The `ValidatorManager` currently only allows to add and remove individual validator addresses, one at a time, but we need it to store the validators' stake as well, and compute the supermajority accordingly.

Furthermore, we should add an `updateValidators()` function, which takes an array of validator addresses and stakes as arguments and updates the stored validators accordingly.

**Comment by yaron-zilliqa** [comment]
Implemented in https://github.com/Zilliqa/zq2/pull/1178.

Added a setValidators method to ValidatorManager.
