### ISSUE TITLE
Extend deposit contract to store UCCB addresses

### ISSUE THREAD

**Issue by DrZoltanFazekas** [Zilliqa/zq2#1127]
Currently, the deposit contract stores only the validators' BLS pubkey and reward address. However, the validators have to sign the `Relayed` events and the UCCB transactions submitted to the target chain, so they need a private key whose address must be stored in the deposit contract.

Furthermore, the deposit contract shall have a function which can be used to retrieve all UCCB addresses and their stake in a single call. It shall also emit events with these data when the `deposit()` or `tempRemoveStaker()` functions are called.

An additional extended version of the `getStakers()` function that returns the stakes along with the BLS pubkeys would be helpful too.

**Comment by yaron-zilliqa** [comment]
Implemented as part of https://github.com/Zilliqa/zq2/pull/1178.
