### ISSUE TITLE
Validator on/off-ramps at epoch boundaries

### ISSUE THREAD

**Issue by theo-zil** [Zilliqa/zq2#1140]
Currently, the validator set can change block to block.
 * Implement epochs as predefined block heights (i.e. intervals specified in number of blocks) when the validator set can change
 * Consider implementing churn limits: i.e. on/off ramp requests would be queued, with some maximum portion of the current validator set being changed on the next epoch and any queued requests above that maximum would be held until the next epoch
 * Consider unbonding (and perhaps bonding?) periods, during which the validator ceases operating but stake is not released. cc @DrZoltanFazekas, I believe they were discussed at one point but I don't recall the conclusion

Some of this has been discussed before, but I don't believe there's an existing document for this (I'm aware of TR-26 and TR-27 for validator logic, but this is a separate feature)

**Comment by DrZoltanFazekas** [comment]
https://github.com/Zilliqa/zilliqa-experimental/blob/users/zoltan/drafts/zoltan/zip-25.md might also contain useful information

**Comment by theo-zil** [comment]
Right, I remembered seeing #904 but couldn't find it when I was opening this issue! I got lost in the TRs and ZIPs.

**Comment by DrZoltanFazekas** [comment]
implemented by #1679
