### ISSUE TITLE
Consider whether checkpoints should be at pre-determined or arbitrary heights

### ISSUE THREAD

**Issue by theo-zil** [Zilliqa/zq2#1181]
Fundamentally, there is almost no reason why nodes shouldn't be free to generate checkpoints whenever they want. The root of trust of a checkpoint is the blockhash, and it's relatively easy to trust any blockhash (e.g. using a trusted block explorer, potentially even verifying headers-only back to genesis if one really feels like it). If nodes generated checkpoints at arbitrary heights, this would likely even allow even faster sync as the interval between any two checkpoints might be lower than a day; it might also enable things like paying a node to export a checkpoint for you right now so you can sync asap.

If this route is taken, the checkpoint trigger mechanism would likely be changed from happening at specific block heights to relying on an external signal. A likely candidate is implementing authenticated `admin_` RPC endpoints for this kind of management functionality. Node operators would then likely run a script alongside the node that is responsible for triggering checkpoints according to the operator's desired policy (and of course have the option to trigger one manually whenever).

One issue with this is regarding checkpoint distribution: currently, this is left to the operator, which leads to mediocre discoverability. The only way to download a checkpoint is to learn where a specific operator uploads its checkpoints files. The URLs could be published on-chain to aid with this.

However, a counter-argument to arbitrary checkpoint heights is if uploading itself is decentralised onto something like IPFS. In that case, it would save significant bandwidth and costs if checkpoints were all at the same coordinated height, and every node generated identical checkpoints: this would allow the IPFS layer to naturally distribute download bandwidth between every node that has generated and pinned said checkpoint. Every node generating checkpoints at arbitrary heights would significantly reduce the efficiency of this.
Of course, this feature is not guaranteed to be on the roadmap yet. Without something like this, there is almost no reason not to enable arbitrary checkpoints.

As a middle-ground, the current automatically-triggered mechanism might be kept if IPFS upload is implemented, but the `admin_triggerCheckpoint` API might also be worth adding for usescases like a paid request for an up-to-date state dump.

**Comment by JamesHinshelwood** [comment]
Closed by #1684
