### ISSUE TITLE
Reduce block time to 1sec on proto-testnet

### ISSUE THREAD

**Issue by DrZoltanFazekas** [Zilliqa/zq2#1217]
The proto-testnet was originally running with 4 validators in the same GCP region and its average block time was ~1sec. When we added 6 more validators running in 2 other regions, i.e. altogether 10 validators in 3 regions (SG, UK, BE), the block time increased to ~2sec. This might be due to network latency and also due to the number of BLS signature verifications the leader has to perform before it can aggregate the votes into a QC (7 out of 10 needed for supermajority). We should figure out what causes the longer block times and try to reduce them back to 1sec before the launch of Jasper.

Note that longer block times are not due to heavy transaction processing - the blocks we're talking about here are empty.

**Comment by JamesHinshelwood** [comment]
Fixed by #1334
