### ISSUE TITLE
Faucet is broken in prototestnet network

### ISSUE THREAD

**Issue by chetan-zilliqa** [Zilliqa/zq2#1219]
I tried to get some funds to my account and received an error from the faucet URL
https://faucet.zq2-prototestnet.zilliqa.com/

![image](https://github.com/user-attachments/assets/37f6b316-70c0-4cc3-907e-245edc9b6aa3)

**Comment by JamesHinshelwood** [comment]
Fixed by https://github.com/Zilliqa/zilliqa-developer/pull/722
