### ISSUE TITLE
Fix scilla testcases

### ISSUE THREAD

**Issue by chetan-zilliqa** [Zilliqa/zq2#1242]
Most of the testcases in https://github.com/Zilliqa/Zilliqa/tree/ba6dc3d1cd08de09ea9f543340c983d83ecdfde7/tests/EvmAcceptanceTests/test/scilla doesn't work. We would need to fix them.

- [x] #1291 
- [x] #1292
- [x] #1293 
- [x] #1294
- [x] #1295
- [x] #1351
- [x] #1426
- [x] #1427
- [x] #1477

**Comment by JamesHinshelwood** [comment]
@saeed-zil will raise more detailed issues for the individual Scilla features we are missing

1. CHAINID
2. _codehash
3. accept
4. TIMESTAMP
5. user-defined libraries
