### ISSUE TITLE
Add zero account as source/sink of rewards/gas respectively

### ISSUE THREAD

**Issue by joseph-zilliqa** [Zilliqa/zq2#1407]
Add a zero account as seen in ZQ1 that will be the source of rewards, and sink of gas used in transactions. This will be useful for the `GetTotalCoinSupply` API endpoint.

**Comment by DrZoltanFazekas** [comment]
... and to ensure the supply has a hard cap of 21bn ZIL

**Comment by JamesHinshelwood** [comment]
Agreed @rrw-zilliqa - I've replaced `null` with `zero`.
