### ISSUE TITLE
Change how we store state to reduce state growth

### ISSUE THREAD

**Issue by DrZoltanFazekas** [Zilliqa/zq2#1503]
Even in absence of transactions the persisted state is growing by approx. 250-300 MB/day. This is because rewards are issued to validators on each block and we produce 86,400 bocks per day and we store state trie updates. We shall consider a more efficient way of storing the state and only construct the trie on the fly to compute its root. Please add your thought @JamesHinshelwood

**Comment by shawn-zil** [comment]
Simple data compression would have minimal impact: 

```
-rw-r--r-- 1 root root 578M Nov 15 04:02 db.sqlite3
-rw-r--r-- 1 root root 262M Nov 15 04:02 test.gz
```

**Comment by shawn-zil** [comment]
This is related to issue #1748

**Comment by shawn-zil** [comment]
Closing for now, as size of SQLite database has gone down by 20% with the SQLite changes. However, if that is insufficient, then we will need an alternative to having an SQLite database and/or choosing a different window to store things e.g. daily data only.
