### ISSUE TITLE
Implement eth_getGasPrice API

### ISSUE THREAD

**Issue by maxconway** [Zilliqa/zq2#1536]
### To-Do List

- [ ] Write tests
- [ ] Rough implementation
- [ ] Finalize and merge PR

**Comment by DrZoltanFazekas** [comment]
The RPC method is called `eth_gasPrice` and is already implemented. Or did you mean another method @maxconway ?

**Comment by maxconway** [comment]
Yeah I was planning to ask about that. I copy pasted it from a list James slacked me a while back. @JamesHinshelwood I'm guessing this is a typo?
