### ISSUE TITLE
GetTxnBodiesForTxBlockEx

### ISSUE THREAD

**Issue by maxconway** [Zilliqa/zq2#1555]
### TODO list

- [x] Write tests
- [x] Draft implementation
- [ ] Finalize and merge

**Comment by JamesHinshelwood** [comment]
@maxconway Do we have an issue for `GetTxBodiesForTxBlock` too? If not, @chetan-zilliqa raised #1587 . Don't ask me what the difference between the non-`Ex` and `Ex` APIs are :)

**Comment by maxconway** [comment]
> @maxconway Do we have an issue for `GetTxBodiesForTxBlock` too? If not, @chetan-zilliqa raised #1587 . Don't ask me what the difference between the non-`Ex` and `Ex` APIs are :)

Nope we don't, I think it just wasn't in the original list.

I think Ex APIs are just paginated versions of the non Ex APIs, so it should be easy enough to do

**Comment by chetan-zilliqa** [comment]
Thanks @maxconway and @JamesHinshelwood , I updated my code and tried to use `GetTxnBodiesForTxBlockEx` API. however , the node displayed this error in response object.
```
{"jsonrpc":"2.0","id":"1","error":{"code":-32603,"message":"Unhandled panic in RPC handler GetTxnBodiesForTxBlockEx"}}
```

On checking the node logs, i found this.
```
024-10-09T05:38:08.358752Z ERROR zilliqa: 62: thread_name="tokio-runtime-worker" index out of bounds: the len is 1 but the index is 1 panic.file="zilliqa/src/api/zil.rs" panic.line=787 panic.column=36
2024-10-09T05:38:08.358956Z ERROR zilliqa::api::zil: 42: e=Unhandled panic in RPC handler GetTxnBodiesForTxBlockEx
```
Note that i am running this API on the converted persistence from ZQ1 to ZQ2. so there may issue with persistence conversion
