### ISSUE TITLE
Block conversion should be run with proper state root hash

### ISSUE THREAD

**Issue by bzawisto** [Zilliqa/zq2#1569]
Currently, converting accounts and blocks are separated and you can run only one of them at a time. If you start with blocks, you don't know what's the state root hash because it hasn't run yet. If you start with accounts, the state root is not printed anywhere so that it can be reused for block conversion.

**Comment by JamesHinshelwood** [comment]
@bzawisto @chetan-zilliqa Is this issue still relevant since we removed the option to convert accounts and blocks separately?
