### ISSUE TITLE
Implement `GetTxnBodiesForTxBlock`

### ISSUE THREAD

**Issue by chetan-zilliqa** [Zilliqa/zq2#1587]
The API is useful and it is used to retrieve the history. Generally TxBlock has microblock hashes. There are two DB's `microblocks_x` and `txBodies_x` where x is 0,1,2 etc(folder) in the `historical_data` folder. of zq1 persistence. The transaction bodies are retrieved using the finalblock(tx block), microblock and txBodies db.

We would need this for history retrieval.

cc @DrZoltanFazekas @JamesHinshelwood @bzawisto

**Comment by chetan-zilliqa** [comment]
Thanks @maxconway and @JamesHinshelwood , I updated my code and tried to use `GetTxnBodiesForTxBlockEx` API. The node displayed this response.
```
curl --request POST   --url http://localhost:4201/   --header 'content-type: application/json'   --data '{
    "id": "1",
    "jsonrpc": "2.0",
    "method": "GetTxnBodiesForTxBlockEx",
    "params": ["7007604","10"]
}'
{"jsonrpc":"2.0","id":"1","result":{"CurrPage":10,"NumPages":1,"Transactions":[]}}
```

So API is fine. I think there is some issue with persistence conversion. maybe it the converter is not handling transaction bodies.

**Comment by maxconway** [comment]
@chetan-zilliqa there bug could still be in the API - I don't know what the bodies are meant to look like so it was quite difficult to test. What does your calling code look like? Is it something I could add as an additional test case?
