### ISSUE TITLE
Implement GetSmartContractSubState API 

### ISSUE THREAD

**Issue by chetan-zilliqa** [Zilliqa/zq2#1588]
`GetSmartContractSubState` allows us to return the substate, variable or structure of a large subset. The API is not currently supported.

for eg:
```
curl --request POST \
  --url http://localhost:4201/ \
  --header 'Content-Type: application/json' \
  --data '{
    "id": "1",
    "jsonrpc": "2.0",
    "method": "GetSmartContractSubState",
	"params": ["zil15tjx2l0gzzxaxucwk50stgw5smthhckl8qcqmf","bnum_req", []]
}'
```

**Comment by chetan-zilliqa** [comment]
cc @DrZoltanFazekas @bzawisto @JamesHinshelwood

**Comment by saeed-zil** [comment]
@chetan-zilliqa Isn't a duplicate of https://github.com/Zilliqa/zq2/issues/1545

**Comment by JamesHinshelwood** [comment]
Duplicate of #1545

**Comment by chetan-zilliqa** [comment]
oh yeah, sorry,  I should have checked before. Thanks @saeed-zil and @JamesHinshelwood
