### ISSUE TITLE
Don't use the faucet address as validator reward address

### ISSUE THREAD

**Issue by DrZoltanFazekas** [Zilliqa/zq2#1618]
In the current ZQ2 test networks, the bootstrap is a validator and it uses the faucet address as reward address. We should change it to use a "neutral" address like all other validators do.

**Comment by JamesHinshelwood** [comment]
Why? Not against doing this, just curious.

**Comment by DrZoltanFazekas** [comment]
My first thought was because it makes harder to check the correctness of the rewards earned by the validator, if they are not sent to a separate account.

On a second thought, I'd start using the null address as reward address for the bootstrap because that is exactly what we will need for the guard nodes we will run with a deposit borrowed from the null address on mainnet i.e. they should not earn rewards.
