### ISSUE TITLE
CreateTransactionResponse struct never includes contract_address in response

### ISSUE THREAD

**Issue by PurrProof** [Zilliqa/zq2#1621]
### CreateTransactionResponse Missing Contract Address in Response

The `CreateTransactionResponse` struct seems to have a field for `contract_address`:

```rust
#[derive(Clone, Serialize, Debug)]
#[serde(rename_all = "PascalCase")]
pub struct CreateTransactionResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub contract_address: Option<Address>,
    pub info: String,
    #[serde(rename = "TranID")]
    pub tran_id: B256,
}
```

However, in the function `create_transaction`:

```rust
fn create_transaction(
    params: Params,
    node: &Arc<Mutex<Node>>,
) -> Result<CreateTransactionResponse> {
    let response = CreateTransactionResponse {
        contract_address: None,
        info: "Txn processed".to_string(),
        tran_id: transaction_hash.0.into(),
    };
    Ok(response)
}
```

The response never contains a `contract_address`, as it's always set to `None`. 

Is this intentional by design, or is it an oversight? I'm aware of the `GetContractAddressFromTransactionID` API, but this struct suggests the contract address should be included in the response.

**Relevant Code:**
- [Struct definition](https://github.com/Zilliqa/zq2/blob/dd2bedef4675910924ab86462a34f2b306f235c1/zilliqa/src/api/types/zil.rs#L138)
- [Implementation](https://github.com/Zilliqa/zq2/blob/dd2bedef4675910924ab86462a34f2b306f235c1/zilliqa/src/api/zil.rs#L205)

**Comment by PurrProof** [comment]
Linked issue: https://github.com/Zilliqa/gozilliqa-sdk/issues/122

**Comment by chetan-zilliqa** [comment]
Thank you, @PurrProof, for reporting this. We’ve resolved the issue on both the SDK and ZQ2 sides.

**Comment by PurrProof** [comment]
Thank you.
I've found another related issue here:
```shell
{
    "id": 0,
    "jsonrpc": "2.0",
    "result": {
        "ContractAddress": "0x7ACb6a641Ad9b3BB9dC947aa019d9B44b4aD572c",
        "Info": "Txn processed",
        "TranID": "0x42d0ddae6ce111353638c12ae2359c84d19e9e59cca751cf5d6d74e0e6bd18d5"
    }
}
```

There should not be those `0x` in the RPC response.
They are not compatible with go-zilliqa sdk (at least):

```shell
TxID: 0x0367a73945cbf76f98a1968fd7d15109008a3a74b03b88f165b8f6f7b2bfe7d3
track 0x0367a73945cbf76f98a1968fd7d15109008a3a74b03b88f165b8f6f7b2bfe7d3
Track error: -20:Txn Hash not Present
```

It happens because gozilliqa-sdk makes such requests:
```shell
{
    "id": 0,
    "jsonrpc": "2.0",
    "method": "GetTransaction",
    "params": [
        "0x42d0ddae6ce111353638c12ae2359c84d19e9e59cca751cf5d6d74e0e6bd18d5"
    ]
}
```

and receives responses:

```shell
{
    "error": {
        "code": -20,
        "message": "Txn Hash not Present"
    },
    "id": 0,
    "jsonrpc": "2.0"
}
```

Moreover, in all examples of the CreateTransaction there are no `0x` in response:

[zq1](https://dev.zilliqa.com/zilliqa1/api/transaction-related-methods/api-transaction-create-tx/)
[zq2](https://dev.zilliqa.com/zilliqa2/api/apis/api/zilliqa/CreateTransaction/)
