### ISSUE TITLE
Underflow on startup with debug builds in zq2devnet

### ISSUE THREAD

**Issue by rrw-zilliqa** [Zilliqa/zq2#1645]
If you attempt to join a node to zq2_devnet with a debug build, you will get a subtraction underflow error in consensus.rs:121 because there's no max supply specified in the config file. With a release build, it will simply underflow.

We should probably check for such things explicitly, and also fix the config file.

**Comment by 86667** [comment]
Im not seeing the same behavior at head of `main`, and the `total_native_token_supply` should be defaulted. Do you remember which commit you saw this on and do you still have the config file?
