### ISSUE TITLE
Z2-Converter API Mainnet : GetTransaction invalid signature error

### ISSUE THREAD

**Issue by chetan-zilliqa** [Zilliqa/zq2#1667]
### Issue Summary:

Calling `GetTransaction` on ZQ2 fails with `invalid signature` error.

Here are the URLs for ZQ1 and ZQ2.
ZQ2 : http://34.124.218.159:4201/
ZQ1 : http://34.124.185.137:4201/

### Result:

**Missing keys:**
```

```
**Different Keys:**
```
 ZQ2 Output (transaction_output_1_ZQ2.json):
{
  "jsonrpc": "2.0",
  "id": 1,
  "error": {
    "code": -32603,
    "message": "invalid signature"
  }
}

 ZQ1 Output (transaction_output_1_zilliqa.json):
{
  "id": 1,
  "jsonrpc": "2.0",
  "result": {
    "ID": "741b86b06f65a0a16f42a7cd5981b32c68899a5719875658374e84cc0bf60c7e",
    "amount": "150646053846153824",
    "gasLimit": "50",
    "gasPrice": "2000000000",
    "nonce": "1422",
    "receipt": {
      "cumulative_gas": "50",
      "epoch_num": "4131493",
      "success": true
    },
    "senderPubKey": "0x0326BBCE46008AB209287185D1FBDF0906C759AC822401332C5F985490459FF6DA",
    "signature": "0x5A1709374026157D7E147985F8178EA52218BD72552D8A4C4362D01A0AEB79AF902BB5BB506EFF7A4F1FF34D70236E6768DFC94388C8E6C38EDC3025D35F89D2",
    "toAddr": "412b55a0ebc1001f930aba8dc107022a3a2ba484",
    "version": "65537"
  }
}



```
### Observations:
The `GetTransaction` API fails with `invalid signature` error on hash `0x741b86b06f65a0a16f42a7cd5981b32c68899a5719875658374e84cc0bf60c7e`

**Comment by chetan-zilliqa** [comment]
If we check https://github.com/Zilliqa/zq2/issues/1666, we find that for some transaction hashes, the `GetTransaction` API works.

**Comment by maxconway** [comment]
Closing as thought to be solved by Bartosz solving a problem with Scilla transactions, we can reopen if we see it occur again
