### ISSUE TITLE
Z2-Converter API Mainnet : GetTxnBodiesForTxBlock

### ISSUE THREAD

**Issue by chetan-zilliqa** [Zilliqa/zq2#1669]
### Issue Summary:
Calling `GetTxnBodiesForTxBlock` on the ZQ1 and ZQ2 has the following diff.
Here are the URLs for ZQ1 and ZQ2.
ZQ2 : http://34.124.218.159:4201/
ZQ1 : http://34.124.185.137:4201/
### Result:
**Missing keys:**
```
```
**Different Keys:**
```
 ZQ2 Output (GetTxnBodiesForTxBlock_output_ZQ2.json):
{
  "jsonrpc": "2.0",
  "id": 1,
  "error": {
    "code": -32603,
    "message": "invalid signature"
  }
}

 ZQ1 Output (GetTxnBodiesForTxBlock_output_zilliqa.json):
{
  "id": 1,
  "jsonrpc": "2.0",
  "result": [
    {
      "ID": "07f759af58a35930e8705380617ed8b71b64eac367baf0f3a2a9b9b908d29466",
      "amount": "50218005776605",
      "gasLimit": "50",
      "gasPrice": "2000000000",
      "nonce": "7819",
      "receipt": {
        "cumulative_gas": "50",
        "epoch_num": "3277414",
        "success": true
      },
      "senderPubKey": "0x02CFF6138379FA7E817E237386893E1A9304B12BC3613669A573BCF1FDEF9B792B",
      "signature": "0x7D5FB0A1EDA1373DA951829AF2FAC8BDE89CCD90483CE2A09FE0C86E397651767CC2827E43B85D278EE40EECB9C340F629614DA6B4AF4F6C40351D6D12DD5AF8",
      "toAddr": "c7fb1d50257f69282ea51b3576c51f88789a2f10",
      "version": "65537"
    },
...
...
...
}
```
### Observations:
The issue is similar to https://github.com/Zilliqa/zq2/issues/1667. Fixing 1667 should also fix this issue unless some other problem.

###  Conclusion:
If the above differences are expected and align with the migration to ZQ2, no further action is required. However, if these differences are unexpected, they may indicate issues that must be addressed.

**Comment by chetan-zilliqa** [comment]
Is it acceptable to have empty parameters for missing keys?

**Comment by maxconway** [comment]
Closing as thought to be solved by Bartosz solving a problem with Scilla transactions, we can reopen if we see it occur again
