### ISSUE TITLE
Z2-Converter API Mainnet : GetSmartContractCode

### ISSUE THREAD

**Issue by chetan-zilliqa** [Zilliqa/zq2#1670]
### Issue Summary:
Calling `GetSmartContractCode` on the ZQ1 and ZQ2 has the following diff.
Here are the URLs for ZQ1 and ZQ2.
ZQ2 : http://34.124.218.159:4201/
ZQ1 : http://34.124.185.137:4201/
### Result:
**Missing keys:**
```
Keys present in ZQ2 but missing in ZQ1:
  root['result']['type']
```
**Different Keys:**
```
```
### Observations:
A new key "type" is added in ZQ2 which says if the transaction is scilla or evm.
```"type": "scilla"```

###  Conclusion:
If the above differences are expected and align with the migration to ZQ2, no further action is required. However, if these differences are unexpected, they may indicate issues that must be addressed.

**Comment by chetan-zilliqa** [comment]
I believe this is fine. No further action is needed for this ticket. It was created solely for reporting purposes to document the differences.
cc @bzawisto @bzawisto @maxconway @JamesHinshelwood

**Comment by maxconway** [comment]
Closing this based on chetan's comment to tidy things up
