### ISSUE TITLE
Z2-Converter API Mainnet : GetBalance

### ISSUE THREAD

**Issue by chetan-zilliqa** [Zilliqa/zq2#1673]
### Issue Summary:
Calling `GetBalance` on the ZQ1 and ZQ2 has the following diff.
Here are the URLs for ZQ1 and ZQ2.
ZQ2 : http://34.124.218.159:4201/
ZQ1 : http://34.124.185.137:4201/
### Result:
**Missing keys:**
```
```
**Different Keys:**
```
Values that differ between ZQ2 and ZQ1:
  root['result']['balance']:
    ZQ2: 5662826498836755835157
    ZQ1: 5662823370927233584237

```
### Observations:
When i query an account balance - `zil1ascnfxmlzl4z3l6ecavxcae5hc37gdzr23enz0` , the API returns a match. However, I used the staking contract address -`zil15lr86jwg937urdeayvtypvhy6pnp6d7p8n5z09`  , and then there is a mismatch.

###  Conclusion:
If the above differences are expected and align with the migration to ZQ2, no further action is required. However, if these differences are unexpected, they may indicate issues that must be addressed.

**Comment by chetan-zilliqa** [comment]
The issue occurred due to the state deltas not being migrated on ZQ2. To address this, we need to ensure that we use the backup taken after the MoveUpdateToDisk operation at the 99th block, with transactions paused before. This approach will guarantee that no state deltas remain in ZQ1's persistence. Do you have any other suggestions, or could you point out any gaps in my understanding?
cc @bzawisto @JamesHinshelwood @DrZoltanFazekas

**Comment by DrZoltanFazekas** [comment]
As discussed, we shall do what you described above @chetan-zilliqa

**Comment by maxconway** [comment]
@chetan-zilliqa Is this fixed now?

**Comment by chetan-zilliqa** [comment]
Closing the issue. The issue is fixed.
