### ISSUE TITLE
Block production stalls when many transactions

### ISSUE THREAD

**Issue by DrZoltanFazekas** [Zilliqa/zq2#1694]
When I send a few hundred transactions to the devnet, after some time the validators stop producing blocks. They are in the same view but time out again and again instead of collecting enough `NewView` messages and creating a block from them. After several minutes they finally recover (i.e. manage to produce a block, update their `highQC` and reset their timeout period to the default 5s) and continue producing blocks or timeouts again. This goes on for 40-50 minutes after which the block production stabilizes.

More details in the Slack thread [https://zilliqa-team.slack.com/archives/C04D147S9QX/p1729696905725669](https://zilliqa-team.slack.com/archives/C04D147S9QX/p1729696905725669)

**Comment by JamesHinshelwood** [comment]
Closing this since testing shows it is resolved.
