### ISSUE TITLE
Implement selfish mining

### ISSUE THREAD

**Issue by 86667** [Zilliqa/zq2#1705]
Currently we broadcast our valid Proposals under the following condition:

```rust
        // Check if minimum block time has elapsed
        if time_since_last_view_change > empty_block_timeout_ms 
```

Which means that we do not wait to include as many transactions as we can before the risk of `NewView` messages being sent, we broadcast as soon as the minimum block time is reached. 

I think this is probably for the best for now but we should consider implementing more selfish mining at some point.

Note that we should not allow `AggQC` proposals to mine selfishly as this could cause further delays when the validator's views are out of sync and not creating proposals.

**Comment by DrZoltanFazekas** [comment]
Isn't this only the case if there are no pending transactions in the mempool to ensure we don't propose empty blocks too fast (within less than 1s)? If there are transactions ready to be included in the block, I'm sure we don't broadcast the `Proposal` after `empty_block_timeout` i.e. 1s

**Comment by 86667** [comment]
> Isn't this only the case if there are no pending transactions in the mempool to ensure we don't propose empty blocks too fast (within less than 1s)? If there are transactions ready to be included in the block, I'm sure we don't broadcast the `Proposal` after `empty_block_timeout` i.e. 1s

This used to be the case up until this PR - https://github.com/Zilliqa/zq2/pull/1573. We always wait for 1 second, transactions or none

**Comment by 86667** [comment]
As @DrZoltanFazekas point out - we sink gas fees and so there is no incentive to include as many transactions in a block as possible.
