### ISSUE TITLE
Restoring devnet from a data folder backup doesn't work

### ISSUE THREAD

**Issue by DrZoltanFazekas** [Zilliqa/zq2#1764]
More details in https://zilliqa-team.slack.com/archives/C04D147S9QX/p1730990455325839?thread_ts=1730983269.927119&cid=C04D147S9QX

**Comment by 86667** [comment]
What we see here is all nodes boot up with:
```
  Based on elapsed clock time of 50204 seconds since lastest view update, jump ahead 13 views
```
This sets their timeout periods to 40960000 ms (~680 mins). And so all nodes do not advance.

One way to mitigate this is to [send NewView messages in the circumstance that a node restarts and jumps views](https://github.com/Zilliqa/zq2/issues/1734). 

I am wondering however how effective this solution would be if multiple nodes restart, as occurred here. A better and more general solution may be to retry sending of `NewView` periodically if we are awaiting an exponential timeout.

**Comment by 86667** [comment]
Fixed at least on of the issues here - https://github.com/Zilliqa/zq2/issues/1734

Another related issue is in progress here - https://github.com/Zilliqa/zq2/issues/1798

I'll close this ticket once both are merged and the tested with the backoff folder linked
