### ISSUE TITLE
Follow Solidity best practices for deposit contract

### ISSUE THREAD

**Issue by JamesHinshelwood** [Zilliqa/zq2#1857]
Find a linter or look up some best practices for Solidity contracts and apply them to the deposit contract.

Lets do things that are reasonable, but skip any 'best practices' that we think are silly :)

**Comment by DrZoltanFazekas** [comment]
A few candidates we can discuss:
- custom errors
- NatSpec comments
- Solidity style guides

**Comment by 86667** [comment]
- [ ] Solhint rules defined and applied to delagate_staking contract [here](https://github.com/Zilliqa/delegated_staking/pull/23)
- [ ] Same rules applied to deposit contracts [here](https://github.com/Zilliqa/zq2/pull/1950)
- [ ] Run solhint as part of zq2 pipeline

**Comment by JamesHinshelwood** [comment]
I'll close this now, since the last change has a PR in a different repo. Thanks @86667 :)
