### ISSUE TITLE
Whitelist EVM contracts imported from ZQ1 that use `scilla_call`

### ISSUE THREAD

**Issue by DrZoltanFazekas** [Zilliqa/zq2#1939]
Here are the sources that contain the contract addresses:
- x-bridge tokens: https://github.com/Zilliqa/xbridge/blob/main/bridge-web/src/config/config.ts
- Plunderswap ZRC2Proxy contracts: https://docs.plunderswap.com/developers/zrc2-proxy-contracts/
- Plunderswap testnet token list: https://tokenlists.org/token-list?url=https://dev-v3.plunderswap.com/lists/default-testnet.json

**Comment by DrZoltanFazekas** [comment]
@lukozill please add further ZQ1 testnet and mainnet contract addresses to be whitelisted here, thanks

**Comment by DrZoltanFazekas** [comment]
### Mainnet
0xe64cA52EF34FdD7e20C0c7fb2E392cc9b4F6D049 SEED
0x63B991C17010C21250a0eA58C6697F696a48cdf3 HRSE
0x241c677D9969419800402521ae87C411897A029f FPS

### Testnet
0x28e8d39Fc68eaA27c88797Eb7D324b4B97D5b844 SEED
0x8618d39a8276D931603c6Bc7306af6A53aD2F1F3 HRSE
0xE90Dd366D627aCc5feBEC126211191901A69f8a0 FPS

**Comment by DrZoltanFazekas** [comment]
## Testnet
ZRC	0x453b11386FBd54bC532892c0217BBc316fc7b918

## Mainnet
zUSDT	0x2274005778063684fbB1BfA96a2b725dC37D75f9
XSGD	0x598FbD8B68a8B7e75b8B7182c750164f348907Bc
zWBTC	0x2938fF251Aecc1dfa768D7d0276eB6d073690317
zETH	0x17D5af5658A24bd964984b36d28e879a8626adC3
XCAD	0xCcF3Ea256d42Aeef0EE0e39Bfc94bAa9Fa14b0Ba
GARY	0xc6F3dede529Af9D98a11C5B32DbF03Bf34272ED5
STREAM	0x7D2fF48c6b59229d448473D267a714d29F078D3E
Lunr	0xE9D47623bb2B3C497668B34fcf61E101a7ea4058
gZIL	0x03A79429acc808e4261a68b0117aCD43Cb0FdBfa
stZIL	0x097C26F8A93009fd9d98561384b5014D64ae17C2
ZOGE	0x01035e423c40a9ad4F6be2E6cC014EB5617c8Bd6
ZILPEPE	0x9C3fE3f471d8380297e4fB222eFb313Ee94DFa0f	
SEED	0xe64cA52EF34FdD7e20C0c7fb2E392cc9b4F6D049
VOID	0x20Dd5D5B5d4C72676514A0eA1052d0200003d69D
ZHIB	0xbfDe2156aF75a29d36614bC1F8005DD816Bd9200

**Comment by DrZoltanFazekas** [comment]
## Testnet
0x5900Ac075A67742f5eA4204650FEad9E674c664F GARY
0x28e8d39fc68eaa27c88797eb7d324b4b97d5b844 SEED
0x51b9f3ddb948bcc16b89b48d83b920bc01dbed55 STREAM
0x1fD09F6701a1852132A649fe9D07F2A3b991eCfA USDC
0x878c5008A348A60a5B239844436A7b483fAdb7F2 WZIL
0x8895Aa1bEaC254E559A3F91e579CF4a67B70ce02 XSGD
0x453b11386FBd54bC532892c0217BBc316fc7b918 ZRC
0xaD581eC62eA08831c8FE2Cd7A1113473fE40A057 kUSD

**Comment by frankmeds** [comment]
property to value in the config file is `consensus.scilla_call_gas_exempt_addrs`

example: 
`consensus.scilla_call_gas_exempt_addrs = ["0x5900Ac075A67742f5eA4204650FEad9E674c664F", "0x28e8d39fc68eaa27c88797eb7d324b4b97d5b844", ...]`
