### ISSUE TITLE
Don't pull transactions from pool unless we are certain they will fit in the block

### ISSUE THREAD

**Issue by JamesHinshelwood** [Zilliqa/zq2#1941]
Currently we pull as many transactions as we can from the pool, execute them and add them if the gas they used is less than the block gas limit. However, this means we sometimes execute a transaction then realise it uses more gas than we can fit and have to undo state changes.

Instead we should only pull transactions from the pool that will *definitely* fit in the block, even if that means excluding some transactions that might have theoretically fit.

**Comment by shawn-zil** [comment]
Done in #1942
