### ISSUE TITLE
Implement expontential backoff for consensus timeout

### ISSUE THREAD

**Issue by theo-zil** [Zilliqa/zq2#359]
See https://github.com/Zilliqa/zq2/pull/339#discussion_r1275568929: when a timeout happens and a `NewView` is broadcast, the timeout should be doubled.
Presumably next time a block is agreed upon in a view, the timeout can then be reset to the default value (@DrZoltanFazekas can confirm?).

**Comment by n-hutton** [comment]
This is completed
