### ISSUE TITLE
Cross-shard messaging MVP

### ISSUE THREAD

**Issue by theo-zil** [Zilliqa/zq2#590]
Tracking issue for the tasks needed to get non-atomic cross-shard messages:

- [x] Add linked pair tracking to the shard registry contract (and a default method for shard contracts to request the creation of one)
- [x] Force nodes to spawn a node of the corresponding shard when a new link is created
- [x] Add either a contract or a precompile that raises the necessary event to alert the node to a cross-shard message
- [x] Implement handling of inter-process messages to make receiving validators include the corresponding transaction in their mempool

MVP notes:
 * Gas will be charged from the sender's account on the target shard. They must have funds already. Self-bootstrapping bridging of funds (and potentially automatic bridging of gas fees) will come later.
 * Only use full clients for now. This will demonstrate cross-chain transactions; light clients will be implemented later.

**Comment by JamesHinshelwood** [comment]
@theo-zil Can this be closed?
