### ISSUE TITLE
Batch verification of AggQC

### ISSUE THREAD

**Issue by n-hutton** [Zilliqa/zq2#706]
The AggQC is not batch verified:
https://github.com/Zilliqa/zq2/blob/main/zilliqa/src/consensus.rs#L1809

**Comment by DrZoltanFazekas** [comment]
The comment in the code claims that calling `verify_messages(agg.signature, &messages, &public_keys)` from bls_signatures
https://docs.rs/bls-signatures/latest/bls_signatures/fn.verify_messages.html
will not work atm - why?

**Comment by DrZoltanFazekas** [comment]
I guess I spotted why it didn't work.

The signatures that are aggregated in an `AggregateQC` were created as part of `NewView` messages by signing the block hash, the view number and the signer's public key in
https://github.com/Zilliqa/zq2/blob/main/zilliqa/src/message.rs#L163-L166

However, the batch verification of the `AggregateQC` uses the signers' indices in the validator set and not their public keys. Thus, we verify the signatures against incorrect messages in
https://github.com/Zilliqa/zq2/blob/main/zilliqa/src/consensus.rs#L1794-L1798

**Comment by JamesHinshelwood** [comment]
Well spotted, thank you :)
