### ISSUE TITLE
Prioritise our own vote before buffered votes

### ISSUE THREAD

**Issue by JamesHinshelwood** [Zilliqa/zq2#720]
Currently when we receive a block proposal, we apply buffered votes for that block immediately, before voting on it ourselves. If we reach a supermajority with solely the buffered votes, our vote is never used. This means we would lose out on the cosigner reward for that block. Therefore, it makes sense to prioritise our own vote before others'.

**Comment by shawn-zil** [comment]
I believe that this naturally happens most of the time - based on observations - that the self-votes get pushed directly into the request-processing queue quite early, independent of the incoming swarm messages.

Closing this issue, unless it's a real thing.
