### ISSUE TITLE
Gas is not tracked properly

### ISSUE THREAD

**Issue by bzawisto** [Zilliqa/zq2#756]
Currently there's some confusion on how gas is calculated. For instance, gas price is compared with gas limit, gas price is given as default value for transaction gas limit, gas units are not properly converted between scilla and evm runs, etc. There should be unified gas tracking mechanism implemented, possibly similar to what has been done in zq1.

**Comment by JamesHinshelwood** [comment]
I think this is fixed since we fixed to revm. Will close, @bzawisto please reopen if I'm wrong.
