### ISSUE TITLE
Otterscan's DS block view doesn't work against zq2

### ISSUE THREAD

**Issue by rrw-zilliqa** [Zilliqa/zq2#882]
.. partly because of the wrong field names in BlockChainInfo, partly because GetDsBlock is not yet implemented.

**Comment by DrZoltanFazekas** [comment]
we'll remove the DS block list and only show TX blocks for now

**Comment by yaron-zilliqa** [comment]
Duplicate of https://github.com/Zilliqa/otterscan/issues/39
