### ISSUE TITLE
Align consensus contract with ZIP-25

### ISSUE THREAD

**Issue by JamesHinshelwood** [Zilliqa/zq2#904]
Specifically I know that we are missing the suspended state for validators, but we should do a full review and make sure we are aligned with https://github.com/Zilliqa/zilliqa-experimental/blob/users/zoltan/drafts/zoltan/zip-25.md

**Comment by JamesHinshelwood** [comment]
Actually ZIP-25 describes the staking contract which sits above our deposit contract, so we shouldn't implement everything in there. We should still make sure we support the necessary core features though.

**Comment by DrZoltanFazekas** [comment]
This is related to or includes #1140

**Comment by DrZoltanFazekas** [comment]
implemented by #1679
